PUT http://localhost:3000/api/orders/64a68e17bfa6f14e10d371b7/pay HTTP/1.1
content-type: application/json

{
    "name": "Decena",
    "email": "decena@gmail.com",
    "password": "lG$53qs1"
}

GET http://localhost:3000/api/keys/paypal


POST http://localhost:3000/api/auth/signup HTTP/1.1
content-type: application/json

{
    "name": "Decena",
    "email": "decena@gmail.com",
    "password": "lG$53qs1"
}


GET http://localhost:3000/api/orders/64a554b3b210fdf702d6dde4

GET http://localhost:3000/api/lockers/123